# suppress-env-warning: ACT
run-name: create packages on publish
on:
  release:
    types:
      created
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      HARPER_VERSION: ${{steps.set-harper-version.outputs.HARPER_VERSION}}

    steps:
      - uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore Harper

      - name: create publish files
        run: dotnet publish Harper -c Release -r linux-x64 --no-restore

      - name: set version output var
        id: set-harper-version
        run: echo "HARPER_VERSION=$(grep -oP '(?<=<FileVersion>)(.*?)(?=</FileVersion>)' Harper/Harper.csproj)" >> $GITHUB_OUTPUT

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: art
          path: |
            pkgconfig/
            Harper/templates/
            Harper/bin/Release/net8.0/linux-x64/publish/

  create-debian-package:
    runs-on: ubuntu-latest
    needs: compile
    env:
      FNAME: harper-v${{needs.compile.outputs.HARPER_VERSION}}
    steps:
      - name: download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: art
          path: ${{github.workspace}}/art

      - name: init directory structure
        run: |
          mkdir -p ${{env.FNAME}}/usr/share/harper/templates
          mkdir -p ${{env.FNAME}}/usr/bin
          mkdir -p ${{env.FNAME}}/usr/lib/systemd/system
          mkdir -p ${{env.FNAME}}/DEBIAN
      - name: copy configuration files
        run: |
          cp art/pkgconfig/harper ${{env.FNAME}}/usr/bin/harper
          cp art/pkgconfig/harper.service ${{env.FNAME}}/usr/lib/systemd/system/harper.service
          cp -r art/Harper/templates/* ${{env.FNAME}}/usr/share/harper/templates
      - name: copy program files
        run: cp -r art/Harper/bin/Release/net8.0/linux-x64/publish/* ${{env.FNAME}}/usr/share/harper

      - name: add executing perms to files
        run: |
          chmod +x \
          ${{env.FNAME}}/usr/share/harper/*.dll \
          ${{env.FNAME}}/usr/share/harper/Harper \
          ${{env.FNAME}}/usr/bin/harper

      - name: create package control file
        run: |
          echo "\
          Package: harper
          Version: ${{needs.compile.outputs.HARPER_VERSION}}
          Description: manages minecraft servers with a discord bot
          Maintainer: thepigeongenerator
          Architecture: all
          Essential: no
          Priority: optional
          Pre-Depends: systemd
          Depends: dotnet-runtime-8.0, default-jre-headless | default-jre | openjdk-11-jre | openjdk-17-jre | openjdk-11-jre | openjdk-8-jre
          " | tee ${{env.FNAME}}/DEBIAN/control

      - name: create debian package
        run: dpkg-deb --build ${{env.FNAME}}

      - name: publish package file
        uses: softprops/action-gh-release@v2
        if: ${{!env.ACT}}
        with:
          tag_name: ${{github.event.release.tag_name || github.event.inputs.release_tag}}
          files: ${{env.FNAME}}.deb
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/upload-artifact@v4
        with:
          path: ${{env.FNAME}}.deb
        if: ${{env.ACT}}
